config/routes.rb
Rails.application.routes.draw do
  post 'commandes/create', to: 'commandes#create'
  get 'commandes/view', to: 'commandes#view'
  resources :pizzas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commande.rb
class Commande < ApplicationRecord
  
  has_many :ligne_commandes
  has_many :pizzas, through: :ligne_commandes
end

app/models/ligne_commande.rb
class LigneCommande < ApplicationRecord
  
  belongs_to :commande, inverse_of: :ligne_commandes
  belongs_to :pizza, inverse_of: :ligne_commandes
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  
  has_many :ligne_commandes
  has_many :commandes, through: :ligne_commandes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commandes_controller.rb
class CommandesController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create]
  before_action :set_commande, only: [:show, :edit, :update, :destroy]

  # GET /commandes
  # GET /commandes.json
  def index
    @commandes = Commande.all
  end

  # GET /commandes/1
  # GET /commandes/1.json
  def show
  end

  # GET /commandes/new
  def new
    @commande = Commande.new
  end

  # GET /commandes/1/edit
  def edit
  end

  # POST /commandes
  # POST /commandes.json
  def create
    @commande = Commande.new(commande_params)
    params.fetch(:pizzas).each do |pizza|
      @commande.pizzas << Pizza.find(pizza)
    end

    respond_to do |format|
      if @commande.save
        format.html { redirect_to @commande, notice: 'Commande was successfully created.' }
        format.json { render :show, status: :created, location: @commande }
      else
        format.html { render :new }
        format.json { render json: @commande.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commandes/1
  # PATCH/PUT /commandes/1.json
  def update
    respond_to do |format|
      if @commande.update(commande_params)
        format.html { redirect_to @commande, notice: 'Commande was successfully updated.' }
        format.json { render :show, status: :ok, location: @commande }
      else
        format.html { render :edit }
        format.json { render json: @commande.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commandes/1
  # DELETE /commandes/1.json
  def destroy
    @commande.destroy
    respond_to do |format|
      format.html { redirect_to commandes_url, notice: 'Commande was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commande
      @commande = Commande.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commande_params
      puts params.inspect
      p params.require(:commande).permit(:nom, :adresse)
      #params.fetch(:commande, {})
    end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :price, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commandes_helper.rb
module CommandesHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/commandes/_form.html.erb
<%= form_with(model: commande, local: true) do |form| %>
  <% if commande.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(commande.errors.count, "error") %> prohibited this commande from being saved:</h2>

      <ul>
      <% commande.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/commandes/edit.html.erb
<h1>Editing Commande</h1>

<%= render 'form', commande: @commande %>

<%= link_to 'Show', @commande %> |
<%= link_to 'Back', commandes_path %>

app/views/commandes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commandes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commandes.each do |commande| %>
      <tr>
        <td><%= link_to 'Show', commande %></td>
        <td><%= link_to 'Edit', edit_commande_path(commande) %></td>
        <td><%= link_to 'Destroy', commande, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commande', new_commande_path %>

app/views/commandes/new.html.erb
<h1>New Commande</h1>

<%= render 'form', commande: @commande %>

<%= link_to 'Back', commandes_path %>

app/views/commandes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_commande_path(@commande) %> |
<%= link_to 'Back', commandes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pizza Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pizzas/_form.html.erb
<%= form_with(model: pizza, local: true) do |form| %>
  <% if pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizzas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzas.each do |pizza| %>
      <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.price %></td>
        <td><%= image_tag pizza.url, style:"height: 10vh; width: 10vw;" %></td>
        <td><%= link_to 'Show', pizza %></td>
        <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
        <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza', new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pizza.price %>
</p>

<p>
  <strong>Url:</strong>
  <%= @pizza.url %>
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>